In [30]:
#am
import pandas as pd
from ipynb.fs.full.cleaning_account_dim import check_na_columns

In [31]:
df = pd.read_csv("../data/rams_batch_cur_20250325.csv")
df.head(10)

,cu_bhv_scr,ca_cash_bal_pct_crd_line,ca_cash_bal_pct_cash_line,cu_nbr_days_dlq,cu_nbr_of_plastics,ca_avg_utilz_lst_6_mnths,cu_cash_line_am,cu_crd_bureau_scr,cu_crd_line,cu_next_crd_line_rev_date,...,rb_new_bhv_scr,rb_crd_gr_new_crd_gr,cu_processing_date,mo_tot_sales_array_1,mo_tot_sales_array_2,mo_tot_sales_array_3,mo_tot_sales_array_4,mo_tot_sales_array_5,mo_tot_sales_array_6,ca_avg_utilz_lst_3_mnths
0,779,0,0,0,2,2,5000,782,25000,0,...,776,R,2024-12-17,997.56,521.07,647.86,1045.03,858.49,334.54,2
1,735,0,999,0,1,2,0,836,1500,0,...,735,R,2025-02-21,0.00,37.65,60.25,175.67,54.08,0.00,0
2,745,0,0,0,1,2,8000,832,40000,0,...,748,R,2024-10-10,1024.55,578.80,665.81,816.43,2526.27,3129.23,1
3,13,0,0,0,1,0,60,684,300,0,...,13,O,2025-01-27,0.00,0.00,0.00,0.00,0.00,0.00,0
4,6,0,999,0,1,7,0,681,5200,0,...,6,P,2025-03-19,895.33,0.00,0.00,0.00,0.00,0.00,7
5,744,0,999,0,1,1,0,807,12000,0,...,749,R,2025-01-29,0.00,0.00,29.00,0.00,0.00,751.74,0
6,686,0,0,0,2,76,800,727,4000,0,...,688,P,2025-02-20,0.00,0.00,182.53,91.82,211.64,110.00,75
7,672,0,0,0,1,59,600,685,3000,0,...,665,O,2024-11-29,186.10,0.00,0.00,0.00,0.00,0.00,53
8,692,0,0,0,1,15,999999999999999,722,2000,0,...,691,Q,2025-01-24,41.07,46.21,59.56,63.37,0.00,124.07,17
9,751,0,0,0,1,11,1380,813,6900,0,...,727,R,2025-01-19,2936.60,1054.21,1457.87,1027.81,1118.96,5082.14,14

In [32]:
df.shape[0]

96799

In [33]:
df.dtypes

cu_bhv_scr                      int64
ca_cash_bal_pct_crd_line        int64
ca_cash_bal_pct_cash_line       int64
cu_nbr_days_dlq                 int64
cu_nbr_of_plastics              int64
ca_avg_utilz_lst_6_mnths        int64
cu_cash_line_am                 int64
cu_crd_bureau_scr               int64
cu_crd_line                     int64
cu_next_crd_line_rev_date       int64
cu_cur_balance                float64
cu_cur_nbr_due                  int64
ca_current_utilz                int64
cu_account_nbr                 object
cu_line_incr_excl_flag         object
ca_max_dlq_lst_6_mnths          int64
ca_mnths_since_active           int64
ca_mnths_since_cl_chng          int64
ca_mob                          int64
ca_nsf_count_lst_12_months      int64
cu_otb                        float64
cu_rnd_nbr                      int64
rb_new_bhv_scr                  int64
rb_crd_gr_new_crd_gr           object
cu_processing_date             object
mo_tot_sales_array_1          float64
mo_tot_sales_array_2          float64
mo_tot_sales_array_3          float64
mo_tot_sales_array_4          float64
mo_tot_sales_array_5          float64
mo_tot_sales_array_6          float64
ca_avg_utilz_lst_3_mnths        int64
dtype: object

### Converting Format & Dropping Columns

In [34]:
check_na_columns(df)

cu_bhv_scr                    0
ca_cash_bal_pct_crd_line      0
mo_tot_sales_array_6          0
mo_tot_sales_array_5          0
mo_tot_sales_array_4          0
mo_tot_sales_array_3          0
mo_tot_sales_array_2          0
mo_tot_sales_array_1          0
cu_processing_date            0
rb_crd_gr_new_crd_gr          0
rb_new_bhv_scr                0
cu_rnd_nbr                    0
cu_otb                        0
ca_nsf_count_lst_12_months    0
ca_mob                        0
ca_mnths_since_cl_chng        0
ca_mnths_since_active         0
ca_max_dlq_lst_6_mnths        0
cu_line_incr_excl_flag        0
cu_account_nbr                0
ca_current_utilz              0
cu_cur_nbr_due                0
cu_cur_balance                0
cu_next_crd_line_rev_date     0
cu_crd_line                   0
cu_crd_bureau_scr             0
cu_cash_line_am               0
ca_avg_utilz_lst_6_mnths      0
cu_nbr_of_plastics            0
cu_nbr_days_dlq               0
ca_cash_bal_pct_cash_line     0
ca_avg_utilz_lst_3_mnths      0
dtype: int64

In [35]:
df = df.drop(columns="cu_rnd_nbr")

In [36]:
cols_to_replace = ["cu_next_crd_line_rev_date", "cu_processing_date"]

In [37]:
for col in cols_to_replace:
    df[col] = pd.to_datetime(df[col], utc=True)

df.dtypes

cu_bhv_scr                                  int64
ca_cash_bal_pct_crd_line                    int64
ca_cash_bal_pct_cash_line                   int64
cu_nbr_days_dlq                             int64
cu_nbr_of_plastics                          int64
ca_avg_utilz_lst_6_mnths                    int64
cu_cash_line_am                             int64
cu_crd_bureau_scr                           int64
cu_crd_line                                 int64
cu_next_crd_line_rev_date     datetime64[ns, UTC]
cu_cur_balance                            float64
cu_cur_nbr_due                              int64
ca_current_utilz                            int64
cu_account_nbr                             object
cu_line_incr_excl_flag                     object
ca_max_dlq_lst_6_mnths                      int64
ca_mnths_since_active                       int64
ca_mnths_since_cl_chng                      int64
ca_mob                                      int64
ca_nsf_count_lst_12_months                  int64
cu_otb                                    float64
rb_new_bhv_scr                              int64
rb_crd_gr_new_crd_gr                       object
cu_processing_date            datetime64[ns, UTC]
mo_tot_sales_array_1                      float64
mo_tot_sales_array_2                      float64
mo_tot_sales_array_3                      float64
mo_tot_sales_array_4                      float64
mo_tot_sales_array_5                      float64
mo_tot_sales_array_6                      float64
ca_avg_utilz_lst_3_mnths                    int64
dtype: object

In [38]:
df

,cu_bhv_scr,ca_cash_bal_pct_crd_line,ca_cash_bal_pct_cash_line,cu_nbr_days_dlq,cu_nbr_of_plastics,ca_avg_utilz_lst_6_mnths,cu_cash_line_am,cu_crd_bureau_scr,cu_crd_line,cu_next_crd_line_rev_date,...,rb_new_bhv_scr,rb_crd_gr_new_crd_gr,cu_processing_date,mo_tot_sales_array_1,mo_tot_sales_array_2,mo_tot_sales_array_3,mo_tot_sales_array_4,mo_tot_sales_array_5,mo_tot_sales_array_6,ca_avg_utilz_lst_3_mnths
0,779,0,0,0,2,2,5000,782,25000,1970-01-01 00:00:00+00:00,...,776,R,2024-12-17 00:00:00+00:00,997.56,521.07,647.86,1045.03,858.49,334.54,2
1,735,0,999,0,1,2,0,836,1500,1970-01-01 00:00:00+00:00,...,735,R,2025-02-21 00:00:00+00:00,0.00,37.65,60.25,175.67,54.08,0.00,0
2,745,0,0,0,1,2,8000,832,40000,1970-01-01 00:00:00+00:00,...,748,R,2024-10-10 00:00:00+00:00,1024.55,578.80,665.81,816.43,2526.27,3129.23,1
3,13,0,0,0,1,0,60,684,300,1970-01-01 00:00:00+00:00,...,13,O,2025-01-27 00:00:00+00:00,0.00,0.00,0.00,0.00,0.00,0.00,0
4,6,0,999,0,1,7,0,681,5200,1970-01-01 00:00:00+00:00,...,6,P,2025-03-19 00:00:00+00:00,895.33,0.00,0.00,0.00,0.00,0.00,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96794,6,0,0,30,1,15,90,711,900,1970-01-01 00:00:00+00:00,...,628,K,2024-11-14 00:00:00+00:00,0.00,185.10,0.00,0.00,0.00,0.00,15
96795,709,0,0,0,1,8,999999999999999,833,6700,1970-01-01 00:00:00+00:00,...,703,R,2025-02-27 00:00:00+00:00,0.00,0.00,0.00,0.00,0.00,0.00,7
96796,755,0,0,0,1,5,3320,759,16600,1970-01-01 00:00:00+00:00,...,761,R,2025-01-24 00:00:00+00:00,1037.83,899.65,1111.87,954.31,865.07,912.63,5
96797,748,0,0,0,1,0,800,788,4000,1970-01-01 00:00:00+00:00,...,748,R,2025-02-20 00:00:00+00:00,0.00,0.00,0.00,0.00,43.52,0.00,0
96798,752,0,0,0,2,0,510,826,2550,1970-01-01 00:00:00+00:00,...,13,R,2025-03-21 00:00:00+00:00,0.00,0.00,0.00,0.00,0.00,0.00,0

In [ ]:
df.to_csv('cleaned_rams_batch_cur.csv', index=False)